/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/addresses/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAddress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/addresses/{address}/nfts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAddressNFTBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBlocks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blocks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBlock"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{address}/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getVerifiedContract"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Server-sent head, reorganization, and sync status events with bounded replay from the durable PostgreSQL event ledger. Last-Event-ID resumes within the retained durable range; malformed, expired, and future cursor values return a typed 400 error, while replay backend failures return a typed 503 error. */
        get: operations["streamHeadEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nfts/{address}/{token_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNFTOwner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nfts/{address}/{token_id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetches the image URI selected only from the current canonical, available PostgreSQL NFT metadata document and returns a freshly retrieved, byte-signature-verified image. The upstream URI is never accepted from the request or exposed in the response, media is never persisted, and every response is no-store. A valid API key is always required; a deployment without configured API-key authentication cannot expose the media proxy anonymously. */
        get: operations["getNFTMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Transactions from one immutable, successfully polled pending-block snapshot. */
        get: operations["listPendingTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sourcify/contracts/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Looks up the configured chain and address through the optional Sourcify adapter. The response is a bounded, validated summary and is not local verification or publication evidence. */
        get: operations["lookupSourcifyContract"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sourcify/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Resolves the address to the newest exact canonical code and creation facts on this server's configured chain, then imports Sourcify compiler input only after its runtime identity matches that local target. The imported input enters the normal durable local verification pipeline and never opts in to a later Sourcify upload. */
        post: operations["importSourcifyContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sourcify/jobs/{verification_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the validated external Sourcify job state. Upstream diagnostic messages and error bodies are never exposed. */
        get: operations["getSourcifyJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBlockStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAggregateStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTokens"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{address}/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTokenTransfers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTransaction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/{hash}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTransactionTrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verification/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitVerificationJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verification/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getVerificationJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verification/jobs/{id}/sourcify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Uploads the compiler input from a durable local verification job. Both its stored submit_to_sourcify opt-in and this call's explicit consent must be true. A successful response contains the external job ticket. */
        post: operations["uploadVerificationJobToSourcify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A 20-byte address; responses use the EIP-55 checksum form. */
        Address: string;
        AddressResponse: {
            data: components["schemas"]["AddressSummary"];
            meta: components["schemas"]["Meta"];
        };
        AddressSummary: {
            address: components["schemas"]["Address"];
            at_block: components["schemas"]["Hash"];
            balance: components["schemas"]["Quantity"];
            code_hash?: components["schemas"]["Hash"];
            completeness: components["schemas"]["Completeness"];
            name?: string;
            nonce: components["schemas"]["Quantity"];
            /** @enum {string} */
            type: "eoa" | "contract" | "delegated_eoa" | "unknown";
        };
        AggregateStats: {
            /** @description Weighted TPS across only blocks with an exact parent interval; omitted when the range has no such interval. */
            average_tps?: components["schemas"]["Decimal"];
            blob_burned_wei: components["schemas"]["Quantity"];
            block_count: components["schemas"]["Quantity"];
            burned_wei: components["schemas"]["Quantity"];
            chain_id: components["schemas"]["Quantity"];
            completeness: components["schemas"]["AggregateStatsCompleteness"];
            from_block: components["schemas"]["Quantity"];
            gas_used: components["schemas"]["Quantity"];
            nft_transfer_count: components["schemas"]["Quantity"];
            snapshot: components["schemas"]["CatalogSnapshot"];
            to_block: components["schemas"]["Quantity"];
            token_event_count: components["schemas"]["Quantity"];
            token_transfer_count: components["schemas"]["Quantity"];
            transaction_count: components["schemas"]["Quantity"];
        };
        AggregateStatsCompleteness: {
            core: boolean;
            stats: boolean;
            token: boolean;
        };
        AggregateStatsResponse: {
            data: components["schemas"]["AggregateStats"];
            meta: components["schemas"]["Meta"];
        };
        APIError: {
            code: string;
            /** @description Stable machine-readable context. A capability_unavailable response may include capability, state, and code identifiers; upstream error text and configured URLs are never included. */
            details?: {
                [key: string]: unknown;
            };
            message: string;
            request_id: string;
        };
        Block: {
            base_fee_per_gas?: components["schemas"]["Quantity"];
            canonical: boolean;
            completeness: components["schemas"]["Completeness"];
            finality: components["schemas"]["Finality"];
            gas_limit?: components["schemas"]["Quantity"];
            gas_used?: components["schemas"]["Quantity"];
            hash: components["schemas"]["Hash"];
            miner?: components["schemas"]["Address"];
            number: components["schemas"]["Quantity"];
            parent_hash: components["schemas"]["Hash"];
            /** Format: date-time */
            timestamp: string;
            transaction_count: number;
        };
        BlockListResponse: {
            data: components["schemas"]["Block"][];
            meta: components["schemas"]["Meta"];
        };
        BlockResponse: {
            data: components["schemas"]["Block"];
            meta: components["schemas"]["Meta"];
        };
        BlockStat: {
            base_fee_per_gas?: components["schemas"]["Quantity"];
            blob_base_fee_per_gas?: components["schemas"]["Quantity"];
            blob_burned_wei?: components["schemas"]["Quantity"];
            blob_gas_used?: components["schemas"]["Quantity"];
            block_hash: components["schemas"]["Hash"];
            block_interval_seconds?: components["schemas"]["Quantity"];
            block_number: components["schemas"]["Quantity"];
            block_timestamp: components["schemas"]["Quantity"];
            burned_wei?: components["schemas"]["Quantity"];
            chain_id: components["schemas"]["Quantity"];
            /** Format: date-time */
            computed_at: string;
            excess_blob_gas?: components["schemas"]["Quantity"];
            gas_limit: components["schemas"]["Quantity"];
            gas_used: components["schemas"]["Quantity"];
            nft_transfer_count: components["schemas"]["Quantity"];
            token_event_count: components["schemas"]["Quantity"];
            token_transfer_count: components["schemas"]["Quantity"];
            transaction_count: components["schemas"]["Quantity"];
            transactions_per_second?: components["schemas"]["Decimal"];
        };
        BlockStatListResponse: {
            data: components["schemas"]["BlockStat"][];
            meta: components["schemas"]["Meta"];
        };
        CatalogSnapshot: {
            block_hash: components["schemas"]["Hash"];
            block_number: components["schemas"]["Quantity"];
            chain_id: components["schemas"]["Quantity"];
        };
        Completeness: {
            core: components["schemas"]["StageState"];
            metadata: components["schemas"]["StageState"];
            state: components["schemas"]["StageState"];
            trace: components["schemas"]["StageState"];
        };
        /** @description A canonical non-negative fixed-point decimal with at most 18 fractional digits. */
        Decimal: string;
        ErrorResponse: {
            error: components["schemas"]["APIError"];
        };
        /** @enum {string} */
        Finality: "pending" | "latest" | "safe" | "finalized" | "orphan";
        /** @description A 32-byte hash; responses use normalized lowercase hexadecimal. */
        Hash: string;
        Meta: {
            chain_id: components["schemas"]["Quantity"];
            coverage_end?: components["schemas"]["Quantity"];
            coverage_start?: components["schemas"]["Quantity"];
            next_cursor?: components["schemas"]["OpaqueCursor"];
            request_id: string;
        };
        NFTBalance: {
            balance: components["schemas"]["Quantity"];
            chain_id: components["schemas"]["Quantity"];
            confidence: components["schemas"]["StateConfidence"];
            owner: components["schemas"]["Address"];
            token_address: components["schemas"]["Address"];
            token_id: components["schemas"]["Quantity"];
        };
        NFTBalanceListResponse: {
            data: components["schemas"]["NFTBalance"][];
            meta: components["schemas"]["Meta"];
        };
        NFTOwnership: {
            balance: components["schemas"]["Quantity"];
            chain_id: components["schemas"]["Quantity"];
            confidence: components["schemas"]["StateConfidence"];
            owner: components["schemas"]["Address"];
            snapshot: components["schemas"]["CatalogSnapshot"];
            token_address: components["schemas"]["Address"];
            token_id: components["schemas"]["Quantity"];
        };
        NFTOwnershipResponse: {
            data: components["schemas"]["NFTOwnership"];
            meta: components["schemas"]["Meta"];
        };
        /** @description A bounded server-issued traversal token that clients must not decode or construct. */
        OpaqueCursor: string;
        PendingMeta: {
            capability: components["schemas"]["StageState"];
            chain_id: components["schemas"]["Quantity"];
            endpoint: string;
            /** Format: date-time */
            expires_at: string;
            next_cursor?: components["schemas"]["OpaqueCursor"];
            request_id: string;
            /** Format: date-time */
            snapshot_at: string;
            snapshot_id: components["schemas"]["Quantity"];
            transaction_count: components["schemas"]["Quantity"];
        };
        PendingTransaction: {
            endpoint: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            first_seen_at: string;
            from: components["schemas"]["Address"];
            gas: components["schemas"]["Quantity"];
            gas_price?: components["schemas"]["Quantity"];
            hash: components["schemas"]["Hash"];
            input: string;
            /** Format: date-time */
            last_seen_at: string;
            max_fee_per_gas?: components["schemas"]["Quantity"];
            max_priority_fee_per_gas?: components["schemas"]["Quantity"];
            nonce: components["schemas"]["Quantity"];
            to?: components["schemas"]["Address"];
            type?: components["schemas"]["Quantity"];
            value: components["schemas"]["Quantity"];
        };
        PendingTransactionListResponse: {
            data: components["schemas"]["PendingTransaction"][];
            meta: components["schemas"]["PendingMeta"];
        };
        PublicConfig: {
            chain_id: components["schemas"]["Quantity"];
            chain_name: string;
            features: {
                [key: string]: boolean;
            };
            native_decimals: number;
            native_name: string;
            native_symbol: string;
        };
        PublicConfigResponse: {
            data: components["schemas"]["PublicConfig"];
            meta: components["schemas"]["Meta"];
        };
        /** @description A uint256 in the inclusive range 0 through 2^256-1, serialized as a canonical decimal string. */
        Quantity: string;
        SearchResponse: {
            data: components["schemas"]["SearchResult"][];
            meta: components["schemas"]["Meta"];
        };
        SearchResult: {
            canonical?: boolean;
            key: string;
            /** @enum {string} */
            kind: "block" | "transaction" | "address" | "contract" | "token" | "nft" | "label";
            label: string;
            rank: number;
        };
        SourcifyContract: {
            address: components["schemas"]["Address"];
            chain_id: components["schemas"]["Quantity"];
            compiler_version?: string;
            contract_identifier?: string;
            creation_match?: components["schemas"]["SourcifyMatch"];
            /** @enum {string} */
            language?: "solidity" | "vyper";
            match?: components["schemas"]["SourcifyMatch"];
            runtime_match?: components["schemas"]["SourcifyMatch"];
        };
        SourcifyContractResponse: {
            data: components["schemas"]["SourcifyContract"];
            meta: components["schemas"]["Meta"];
        };
        SourcifyImportRequest: {
            address: components["schemas"]["Address"];
            /** @description Optional constructor-argument suffix, accepted only when it matches the canonical creation input. */
            constructor_arguments?: string;
        };
        SourcifyJob: {
            contract?: components["schemas"]["SourcifyContract"];
            /** @enum {string} */
            state: "pending" | "succeeded" | "failed";
            /** Format: uuid */
            verification_id: string;
        };
        SourcifyJobResponse: {
            data: components["schemas"]["SourcifyJob"];
            meta: components["schemas"]["Meta"];
        };
        /** @enum {string} */
        SourcifyMatch: "match" | "exact_match";
        SourcifyTicket: {
            /** Format: uuid */
            verification_id: string;
        };
        SourcifyTicketResponse: {
            data: components["schemas"]["SourcifyTicket"];
            meta: components["schemas"]["Meta"];
        };
        SourcifyUploadRequest: {
            /**
             * @description Explicit consent for this irreversible external source upload.
             * @enum {boolean}
             */
            consent: true;
        };
        /** @enum {string} */
        StageState: "complete" | "pending" | "unavailable" | "failed";
        /**
         * @description State observed by an exact block-hash RPC call and rechecked against canonicality.
         * @enum {string}
         */
        StateConfidence: "rpc_exact";
        Status: {
            /** @description Whether canonical coverage is contiguous from the configured start through the latest known head. */
            backfill_complete: boolean;
            chain_id: components["schemas"]["Quantity"];
            completeness: components["schemas"]["Completeness"];
            core_ready: boolean;
            finalized_block?: components["schemas"]["Quantity"];
            /** @description Highest canonical block stored in any coverage range; absent before the first block is stored. */
            highest_covered_block?: components["schemas"]["Quantity"];
            /** @description Highest canonical block contiguous from the configured start block. */
            indexed_block: components["schemas"]["Quantity"];
            lag: components["schemas"]["Quantity"];
            latest_block: components["schemas"]["Quantity"];
            safe_block?: components["schemas"]["Quantity"];
        };
        StatusResponse: {
            data: components["schemas"]["Status"];
            meta: components["schemas"]["Meta"];
        };
        TokenContract: {
            address: components["schemas"]["Address"];
            chain_id: components["schemas"]["Quantity"];
            code_hash: components["schemas"]["Hash"];
            /** @enum {string} */
            confidence: "verified" | "high" | "inferred" | "guess";
            decimals?: number;
            metadata_state: string;
            name?: string;
            observed_block_hash: components["schemas"]["Hash"];
            observed_block_number: components["schemas"]["Quantity"];
            /** @enum {string} */
            standard: "erc20" | "erc721" | "erc1155" | "unknown";
            symbol?: string;
            total_supply?: components["schemas"]["Quantity"];
            /** Format: date-time */
            updated_at: string;
        };
        TokenEvent: {
            amount?: components["schemas"]["Quantity"];
            block_hash: components["schemas"]["Hash"];
            block_number: components["schemas"]["Quantity"];
            chain_id: components["schemas"]["Quantity"];
            confidence: string;
            from?: components["schemas"]["Address"];
            kind: string;
            log_index: components["schemas"]["Quantity"];
            operator?: components["schemas"]["Address"];
            standard: string;
            sub_index: components["schemas"]["Quantity"];
            to?: components["schemas"]["Address"];
            token_address: components["schemas"]["Address"];
            token_id?: components["schemas"]["Quantity"];
            transaction_hash: components["schemas"]["Hash"];
        };
        TokenEventListResponse: {
            data: components["schemas"]["TokenEvent"][];
            meta: components["schemas"]["Meta"];
        };
        TokenListResponse: {
            data: components["schemas"]["TokenContract"][];
            meta: components["schemas"]["Meta"];
        };
        TokenResponse: {
            data: components["schemas"]["TokenContract"];
            meta: components["schemas"]["Meta"];
        };
        TraceFrame: {
            call_type: string;
            created_address?: components["schemas"]["Address"];
            depth: number;
            error?: string;
            from?: components["schemas"]["Address"];
            gas?: components["schemas"]["Quantity"];
            gas_used?: components["schemas"]["Quantity"];
            input?: string;
            output?: string;
            parent_path: number[];
            path: number[];
            reverted: boolean;
            to?: components["schemas"]["Address"];
            value?: components["schemas"]["Quantity"];
        };
        Transaction: {
            block_hash?: components["schemas"]["Hash"];
            block_number?: components["schemas"]["Quantity"];
            canonical: boolean;
            completeness: components["schemas"]["Completeness"];
            finality: components["schemas"]["Finality"];
            from: components["schemas"]["Address"];
            gas: components["schemas"]["Quantity"];
            gas_price?: components["schemas"]["Quantity"];
            hash: components["schemas"]["Hash"];
            input: string;
            max_fee_per_gas?: components["schemas"]["Quantity"];
            max_priority_fee_per_gas?: components["schemas"]["Quantity"];
            nonce: components["schemas"]["Quantity"];
            /** @enum {string} */
            status?: "pending" | "success" | "failed" | "unknown";
            to?: components["schemas"]["Address"];
            transaction_index?: number;
            type?: string;
            value: components["schemas"]["Quantity"];
        };
        TransactionListResponse: {
            data: components["schemas"]["Transaction"][];
            meta: components["schemas"]["Meta"];
        };
        TransactionResponse: {
            data: components["schemas"]["Transaction"];
            meta: components["schemas"]["Meta"];
        };
        TransactionTrace: {
            block_hash: components["schemas"]["Hash"];
            block_number: components["schemas"]["Quantity"];
            chain_id: components["schemas"]["Quantity"];
            frames: components["schemas"]["TraceFrame"][];
            /** @enum {string} */
            state: "complete" | "missing" | "unavailable" | "failed";
            transaction_hash: components["schemas"]["Hash"];
            transaction_index: components["schemas"]["Quantity"];
        };
        TransactionTraceResponse: {
            data: components["schemas"]["TransactionTrace"];
            meta: components["schemas"]["Meta"];
        };
        VerificationJob: {
            /** Format: date-time */
            created_at: string;
            creation_match?: components["schemas"]["VerificationMatch"];
            error_code?: string;
            /** Format: uuid */
            id: string;
            published?: boolean;
            result_kind?: components["schemas"]["VerificationMatch"];
            runtime_match?: components["schemas"]["VerificationMatch"];
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
            /** Format: date-time */
            updated_at: string;
        };
        VerificationJobResponse: {
            data: components["schemas"]["VerificationJob"];
            meta: components["schemas"]["Meta"];
        };
        /** @enum {string} */
        VerificationMatch: "exact" | "metadata_only" | "mismatch";
        VerificationSubmission: {
            address: components["schemas"]["Address"];
            compiler_version: string;
            /** @description Optional constructor-argument suffix. The server accepts it only when it is an exact suffix of the canonical creation input and removes it before enqueueing. */
            constructor_arguments?: string;
            contract_identifier: string;
            /** @enum {string} */
            language: "solidity" | "vyper";
            /**
             * @description Optional Etherscan-compatible source-license identifier stored only as publication metadata.
             * @enum {string}
             */
            license_type?: "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10" | "11" | "12" | "13" | "14";
            /** @description Inline-source Standard JSON compiler input. The service preserves code-generation settings but replaces outputSelection with the bounded exact-target fields required for deterministic matching before persisting the request. */
            standard_json: {
                [key: string]: unknown;
            };
            /** @default false */
            submit_to_sourcify: boolean;
        };
        VerifiedContract: {
            abi: {
                [key: string]: unknown;
            }[];
            address: components["schemas"]["Address"];
            chain_id: components["schemas"]["Quantity"];
            code_hash: components["schemas"]["Hash"];
            compiler_version: string;
            contract_name: string;
            /** Format: date-time */
            created_at: string;
            /** @enum {string} */
            language: "solidity" | "vyper";
            match_kind: components["schemas"]["VerificationMatch"];
            settings: {
                [key: string]: unknown;
            };
            sources: {
                [key: string]: unknown;
            };
            valid_from_block: components["schemas"]["Quantity"];
            valid_to_block?: components["schemas"]["Quantity"];
        };
        VerifiedContractResponse: {
            data: components["schemas"]["VerifiedContract"];
            meta: components["schemas"]["Meta"];
        };
    };
    responses: {
        /** @description Machine-readable error. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        Address: components["schemas"]["Address"];
        Cursor: components["schemas"]["OpaqueCursor"];
        Limit: number;
        TransactionHash: components["schemas"]["Hash"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address: components["parameters"]["Address"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Address summary at one canonical block. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddressResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listAddressNFTBalances: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                address: components["parameters"]["Address"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Positive canonical ERC-721/ERC-1155 balances for an owner. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NFTBalanceListResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listBlocks: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical blocks ordered newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockListResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Decimal/hex block number or 32-byte block hash. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Block selected by canonical height or exact hash. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getPublicConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public, non-secret deployment configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicConfigResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getVerifiedContract: {
        parameters: {
            query: {
                code_hash: components["schemas"]["Hash"];
            };
            header?: never;
            path: {
                address: components["parameters"]["Address"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verified contract artifact bound to the requested code hash. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifiedContractResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    streamHeadEvents: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["Error"];
            503: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    getNFTOwner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address: components["parameters"]["Address"];
                token_id: components["schemas"]["Quantity"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical NFT ownership or balance for one token instance. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NFTOwnershipResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getNFTMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address: components["parameters"]["Address"];
                token_id: components["schemas"]["Quantity"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Freshly fetched PNG, JPEG, GIF, WebP, or AVIF image. */
            200: {
                headers: {
                    /** @description Always `no-store, max-age=0`. */
                    "Cache-Control"?: string;
                    /** @description Fixed safe inline filename derived only from the validated media type. */
                    "Content-Disposition"?: string;
                    /** @description Restrictive policy for an untrusted binary response. */
                    "Content-Security-Policy"?: string;
                    /** @description Always `nosniff`. */
                    "X-Content-Type-Options"?: string;
                    /** @description Always `available` for a successful response. */
                    "X-Etherview-Media-State"?: "available";
                    [name: string]: unknown;
                };
                content: {
                    "image/avif": string;
                    "image/gif": string;
                    "image/jpeg": string;
                    "image/png": string;
                    "image/webp": string;
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            413: components["responses"]["Error"];
            422: components["responses"]["Error"];
            502: components["responses"]["Error"];
            503: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    listPendingTransactions: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending transactions ordered by first-seen time and hash, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingTransactionListResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    search: {
        parameters: {
            query: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked, non-auto-redirecting search results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    lookupSourcifyContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address: components["parameters"]["Address"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validated Sourcify contract summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcifyContractResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    importSourcifyContract: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourcifyImportRequest"];
            };
        };
        responses: {
            /** @description An equivalent local verification job already exists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationJobResponse"];
                };
            };
            /** @description Imported verification job accepted for local execution. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationJobResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSourcifyJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Sourcify verification ticket ID. */
                verification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current external verification job state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcifyJobResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getBlockStats: {
        parameters: {
            query: {
                from_block: components["schemas"]["Quantity"];
                to_block: components["schemas"]["Quantity"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Complete canonical per-block statistics for a closed range. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockStatListResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAggregateStats: {
        parameters: {
            query: {
                from_block: components["schemas"]["Quantity"];
                to_block: components["schemas"]["Quantity"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical aggregate statistics with explicit range completeness. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AggregateStatsResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current indexing and capability status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listTokens: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discovered token contracts at a stable canonical snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenListResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                address: components["parameters"]["Address"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A discovered token contract and metadata state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listTokenTransfers: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                address: components["parameters"]["Address"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical token events ordered newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenEventListResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listTransactions: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canonical transactions ordered by block and transaction index, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionListResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hash: components["parameters"]["TransactionHash"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction and current inclusion. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getTransactionTrace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hash: components["parameters"]["TransactionHash"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Normalized canonical transaction call tree. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionTraceResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    submitVerificationJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificationSubmission"];
            };
        };
        responses: {
            /** @description An equivalent verification job already exists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationJobResponse"];
                };
            };
            /** @description Verification job accepted for asynchronous execution. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationJobResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getVerificationJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current verification job state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationJobResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    uploadVerificationJobToSourcify: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Durable local verification job ID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourcifyUploadRequest"];
            };
        };
        responses: {
            /** @description Sourcify accepted the upload and returned an external ticket. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcifyTicketResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
