"""Build and test every locked Vyper runtime on the current native platform.

Artifacts are local outputs. Publication and signing are separate operations.
Requires uv 0.12.12; production helpers do not contain uv or pip.
"""
import argparse
import concurrent.futures
import hashlib
import json
import os
from pathlib import Path
import platform
import shutil
import subprocess
import tarfile
import tempfile
import urllib.request

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]


def run(args, **kwargs):
    subprocess.run(args, check=True, **kwargs)


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def install_source(item, python, cache):
    # 0.2.0 has an official Git release but no PyPI artifact. Reconstitute only
    # the git-version packaging file normally generated by upstream setup.py.
    source = cache / "compiler.tar.gz"
    with urllib.request.urlopen(item["source_url"], timeout=60) as response:
        raw = response.read(16 * 1024 * 1024 + 1)
    if len(raw) > 16 * 1024 * 1024 or hashlib.sha256(raw).hexdigest() != item["compiler_sha256"]:
        raise ValueError("official compiler source digest mismatch")
    source.write_bytes(raw)
    with tempfile.TemporaryDirectory(prefix="vyper-source-") as temporary:
        with tarfile.open(source) as archive:
            # Python used to orchestrate builds supports the safe data filter.
            archive.extractall(temporary, filter="data")
        tree = next(Path(temporary).iterdir())
        commit = item["source_url"].rsplit("/", 1)[1].removesuffix(".tar.gz")
        (tree / "vyper/vyper_git_version.txt").write_text(commit)
        run(["uv", "pip", "install", "--python", python, "--no-deps", "--no-build-isolation", str(tree)], cwd=temporary)


def verify_runtime(item, helper):
    version = item["version"]
    fixtures = ROOT / "internal/verify/testdata/compiler/vyper/versions" / version
    run([str(helper), "--self-test"], env={})
    count = 0
    for source in sorted(fixtures.glob("*.input.json")):
        for suffix in ("input", "modified"):
            prefix = source.name.removesuffix(".input.json")
            request = fixtures / (prefix + "." + suffix + ".json")
            expected = fixtures / (prefix + (".output.json" if suffix == "input" else ".modified_output.json"))
            result = subprocess.run([str(helper), "--compile", str(5 << 20), str(32 << 20)], input=request.read_bytes(), capture_output=True, env={}, timeout=120, check=True)
            actual, reference = json.loads(result.stdout), json.loads(expected.read_bytes())
            # Diagnostics contain version-specific source locations; compare
            # diagnostic outcomes, and all successful compiler artifacts.
            if prefix.startswith("invalid"):
                if not any(error.get("severity") == "error" for error in actual.get("errors", [])):
                    raise ValueError("invalid source compiled")
            elif actual.get("contracts") != reference.get("contracts"):
                raise ValueError("runtime differs from official reference: " + version + "/" + prefix)
            count += 1
    if count < 6:
        raise ValueError("incomplete compiler fixture matrix")
    return count


def build(item, cache, output):
    version = item["version"]
    workspace = cache / version
    workspace.mkdir(parents=True, exist_ok=True)
    venv = workspace / "build-venv"
    run(["uv", "venv", "--allow-existing", "--python", item["python"], str(venv)])
    python = str(venv / "bin/python")
    run(["uv", "pip", "sync", "--python", python, "--require-hashes", "--only-binary=:all:", str(HERE / "versions" / (version + ".lock"))])
    if version == "0.2.0":
        install_source(item, python, workspace)
    run(["uv", "pip", "check", "--python", python])
    runtime = workspace / "runtime"
    if runtime.exists():
        for path in [runtime, *runtime.rglob("*")]:
            if path.is_dir():
                path.chmod(0o700)
        shutil.rmtree(runtime)
    run([python, str(HERE / "build.py"), str(runtime)], env={**os.environ, "ETHERVIEW_VYPER_BUILD_VERSION": version})
    tested = verify_runtime(item, runtime / "etherview-vyper")
    manifest = json.loads((runtime / "runtime-manifest.json").read_bytes())
    name = "vyper-" + version + "-" + manifest["platform"]
    archive_path = output / (name + ".tar.gz")
    with tarfile.open(archive_path, "w:gz", format=tarfile.USTAR_FORMAT) as archive:
        for path in sorted(runtime.rglob("*")):
            if path.is_file():
                info = archive.gettarinfo(str(path), path.relative_to(runtime).as_posix())
                info.uid = info.gid = info.mtime = 0
                info.uname = info.gname = ""
                with path.open("rb") as stream:
                    archive.addfile(info, stream)
    descriptor = {"version": version, "compiler_sha256": item["compiler_sha256"], "platform": manifest["platform"], "sha256": digest(archive_path), "manifest_sha256": digest(runtime / "runtime-manifest.json"), "max_bytes": archive_path.stat().st_size, "protocol": manifest["schema"], "archive": archive_path.name, "fixture_cases": tested}
    (output / (name + ".json")).write_text(json.dumps(descriptor, sort_keys=True) + "\n")
    print("verified", version, manifest["platform"], tested, flush=True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", action="append")
    parser.add_argument("--jobs", type=int, default=2, choices=range(1, 5))
    parser.add_argument("--output", type=Path, default=ROOT / ".local/vyper-releases")
    args = parser.parse_args()
    if not subprocess.check_output(["uv", "--version"], text=True).startswith("uv 0.12.12"):
        raise ValueError("uv 0.12.12 required")
    entries = json.loads((HERE / "versions/index.json").read_text())["versions"]
    if args.version:
        entries = [entry for entry in entries if entry["version"] in args.version]
        if len(entries) != len(set(args.version)):
            raise ValueError("unknown locked compiler version")
    cache = ROOT / ".local/vyper-builds"
    args.output.mkdir(parents=True, exist_ok=True)
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.jobs) as pool:
        list(pool.map(lambda entry: build(entry, cache, args.output), entries))


if __name__ == "__main__":
    main()
