{{- if .Values.externalSecret.enabled }}
apiVersion: {{ .Values.externalSecret.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "etherview.fullname" . }}
  labels:
    {{- include "etherview.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.secrets.existingSecret | quote }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.secrets.databaseURLKey | quote }}
      remoteRef:
        key: {{ .Values.externalSecret.databaseURLRemoteKey | quote }}
    - secretKey: {{ .Values.secrets.rpcURLsKey | quote }}
      remoteRef:
        key: {{ .Values.externalSecret.rpcURLsRemoteKey | quote }}
    - secretKey: {{ .Values.secrets.apiKeyPepperKey | quote }}
      remoteRef:
        key: {{ .Values.externalSecret.apiKeyPepperRemoteKey | quote }}
    {{- with .Values.externalSecret.natsURLRemoteKey }}
    - secretKey: {{ $.Values.secrets.natsURLKey | quote }}
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
    {{- with .Values.externalSecret.redisURLRemoteKey }}
    - secretKey: {{ $.Values.secrets.redisURLKey | quote }}
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
    {{- with .Values.externalSecret.s3AccessKeyRemoteKey }}
    - secretKey: {{ $.Values.secrets.s3AccessKeyKey | quote }}
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
    {{- with .Values.externalSecret.s3SecretKeyRemoteKey }}
    - secretKey: {{ $.Values.secrets.s3SecretKeyKey | quote }}
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
    {{- with .Values.externalSecret.s3SessionTokenRemoteKey }}
    - secretKey: {{ $.Values.secrets.s3SessionTokenKey | quote }}
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
    {{- with .Values.externalSecret.otlpTraceEndpointRemoteKey }}
    - secretKey: {{ $.Values.secrets.otlpTraceEndpointKey | quote }}
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
    {{- with .Values.externalSecret.otlpTraceHeadersRemoteKey }}
    - secretKey: {{ $.Values.secrets.otlpTraceHeadersKey | quote }}
      remoteRef:
        key: {{ . | quote }}
    {{- end }}
{{- end }}
