{{- if .Values.externalSecret.enabled }}
apiVersion: {{ .Values.externalSecret.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "etherview.fullname" . }}
  labels:
    {{- include "etherview.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.secrets.existingSecret }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.secrets.databaseURLKey }}
      remoteRef:
        key: {{ .Values.externalSecret.databaseURLRemoteKey }}
    - secretKey: {{ .Values.secrets.rpcURLsKey }}
      remoteRef:
        key: {{ .Values.externalSecret.rpcURLsRemoteKey }}
    - secretKey: {{ .Values.secrets.apiKeyPepperKey }}
      remoteRef:
        key: {{ .Values.externalSecret.apiKeyPepperRemoteKey }}
{{- end }}
